repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest version
    hooks:
      - id: black
        args:
          - --line-length=88

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version
    hooks:
      - id: isort
        args:
          - --profile=black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args:
          - --maxkb=30000000
    -   id: check-ast
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-xml
    -   id: pretty-format-json
        args:
          - --autofix

  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0  # pick a git hash / tag to point to
    hooks:
    - id: pydocstyle
      args:
      - --ignore=D401,D417,D100,D407,D406,D413,D212,D203,D104,D205

  - repo: https://github.com/DHBW-Smart-Rollerz/smarty_hooks
    rev: v0.1.1
    hooks:
      - id: ament_uncrustify

exclude: '.vscode/'
